<a href="https://colab.research.google.com/github/202422/Delivery-Duration-Prediction/blob/main/Modeling/Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
import pandas as pd
from sklearn.svm import SVR
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor

In [ ]:
pd.set_option("display.max_columns", None)

In [ ]:
df = pd.read_csv("/content/dataset_features_handled.csv")

In [ ]:
df

,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,Delivery_Duration,created_at_month,created_at_day,created_at_hour,created_at_minutes,actual_delivery_time_month,actual_delivery_time_day,actual_delivery_time_hour,actual_delivery_time_minutes,creation_period_day
0,4,1,0.881706,0.976818,1.417316,-0.225554,0.491667,-0.174460,-0.822359,-0.655351,1.525031,1.588659,3779,2,6,22,24,2,6,23,27,4
1,45,2,-1.189868,-0.294604,-1.195571,1.943361,0.914430,-1.339853,-1.283129,-1.138113,1.525031,0.763220,4024,2,10,21,49,2,10,22,56,4
2,35,3,0.881706,2.074152,0.546354,0.451107,1.450106,-1.084923,-1.129539,-0.731576,1.525031,-1.172459,1586,2,16,0,11,2,16,0,38,1
3,37,1,-1.189868,-0.604002,-1.195571,2.264968,1.242663,-1.194179,-1.129539,-0.985662,1.525031,1.270069,2273,2,12,3,36,2,12,4,14,1
4,37,1,-0.499343,1.124505,-0.324609,2.007682,3.001989,-1.194179,-1.167937,-1.011070,1.525031,-1.577937,2988,1,27,2,12,1,27,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136477,27,4,0.191182,-0.716211,0.546354,-0.770999,-1.057591,-0.757157,-0.707167,-0.604534,-0.650744,-0.969719,3907,2,17,0,19,2,17,1,24,1
136478,27,4,2.262756,0.621216,1.417316,-0.616627,-0.595439,-0.939249,-0.937552,-0.833211,-0.650744,1.849324,3383,2,13,0,1,2,13,0,58,1
136479,27,4,1.572231,-0.347408,0.546354,-0.886777,-1.714056,0.044051,0.214373,-0.172589,-0.650744,1.270069,3008,1,24,4,46,1,24,5,36,1
136480,57,1,-1.189868,-0.892774,-1.195571,-0.282157,-1.356939,-1.121342,-1.091142,-0.884028,1.525031,-0.713881,3907,2,1,18,18,2,1,19,23,4
136481,57,1,0.881706,0.287066,1.417316,-0.565170,-0.792379,-0.647901,-0.591974,-0.604534,1.525031,-1.920664,2228,2,8,19,24,2,8,20,1,4

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(df.drop("Delivery_Duration", axis = 1), df["Delivery_Duration"], test_size=0.2)

In [ ]:
X_test

,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,created_at_month,created_at_day,created_at_hour,created_at_minutes,actual_delivery_time_month,actual_delivery_time_day,actual_delivery_time_hour,actual_delivery_time_minutes,creation_period_day
11729,2,4,0.191182,-0.872148,0.546354,-0.629492,-0.674215,0.116888,0.060783,0.157722,-0.650744,1.472808,2,3,19,51,2,3,20,52,4
92685,54,5,-0.499343,0.519734,-0.324609,1.271847,2.216857,2.047070,1.980659,1.885502,-0.650744,-0.100836,1,28,3,3,1,28,3,57,1
113727,71,1,0.191182,0.188058,0.546354,-0.179242,-0.411629,-1.376272,-1.359924,-1.188930,1.525031,-0.878004,2,10,21,8,2,10,21,43,4
85894,10,3,0.191182,0.600590,0.546354,0.386785,0.638715,1.282281,1.059118,1.047021,-0.650744,0.048805,1,30,19,57,1,30,20,41,4
47024,49,3,-0.499343,0.262314,-0.324609,0.142364,0.586198,0.626747,0.636746,0.615076,-0.650744,1.704510,1,22,2,37,1,22,3,35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,54,1,0.191182,1.759803,0.546354,0.078043,1.872869,-0.502227,-0.399987,-0.299631,1.525031,1.501771,2,1,21,17,2,1,22,25,4
51590,4,5,-0.499343,-0.665882,-0.324609,-0.758134,0.126672,-0.720738,-0.783962,-0.858619,-0.650744,-1.413815,2,11,22,14,2,11,22,47,4
108671,4,1,1.572231,2.933868,1.417316,0.978541,0.323612,-0.138042,0.943926,0.081497,1.525031,0.768047,1,26,0,20,1,26,1,15,1
15492,27,4,0.881706,-1.197223,-0.324609,-1.249549,-1.897866,-0.174460,0.751938,-0.299631,-0.650744,-0.660783,1,27,4,29,1,27,4,57,1
20761,45,4,0.191182,-0.000056,0.546354,-0.374779,-0.506160,-1.084923,-1.014347,-0.960253,1.525031,-0.520796,2,8,18,0,2,8,19,41,4

In [ ]:
Y_train

128703    3688
98741     3400
47427     2572
86161     2422
86572     4364
          ...
67796     3109
91745     2214
59718      975
51321     1840
124784    2318
Name: Delivery_Duration, Length: 109185, dtype: int64

In [ ]:
df.corr()["Delivery_Duration"].sort_values(ascending = False)

Delivery_Duration                               1.000000
estimated_store_to_consumer_driving_duration    0.210071
subtotal                                        0.144875
total_outstanding_orders                        0.112479
estimated_order_place_duration                  0.102188
max_item_price                                  0.102140
num_distinct_items                              0.100346
total_items                                     0.089848
actual_delivery_time_month                      0.075228
created_at_month                                0.074770
total_busy_dashers                              0.015425
min_item_price                                  0.003101
store_primary_category                         -0.003896
actual_delivery_time_minutes                   -0.004698
total_onshift_dashers                          -0.005271
created_at_minutes                             -0.007072
order_protocol                                 -0.073517
actual_delivery_time_day                       -0.078085
created_at_day                                 -0.078429
actual_delivery_time_hour                      -0.128961
creation_period_day                            -0.140680
created_at_hour                                -0.142308
Name: Delivery_Duration, dtype: float64

In [ ]:
important_feat = ["estimated_store_to_consumer_driving_duration", "subtotal", "total_outstanding_orders", "estimated_order_place_duration",
                  "max_item_price", "num_distinct_items", "created_at_hour", "creation_period_day" ]

In [ ]:
model_svr = SVR()

param_grid = {"kernel": ["rbf", "linear", "poly"],
              "C": [0.001, 0.01, 0.1, 1, 10, 100]
              }

grid = GridSearchCV(model_svr, cv = 5, param_grid=param_grid)

In [ ]:
model_svr_simple = SVR(kernel = "poly", C = 1)
model_svr_simple.fit(X_train[important_feat], Y_train)

SVR(C=1, kernel='poly')

In [ ]:
model_randomF_simple = RandomForestRegressor(random_state=3, n_estimators=300, n_jobs=-1, verbose = 2)
model_randomF_simple.fit(X_train[important_feat], Y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.

building tree 1 of 300
building tree 2 of 300
building tree 3 of 300
building tree 4 of 300
building tree 5 of 300
building tree 6 of 300
building tree 7 of 300
building tree 8 of 300
building tree 9 of 300
building tree 10 of 300
building tree 11 of 300
building tree 12 of 300
building tree 13 of 300
building tree 14 of 300
building tree 15 of 300
building tree 16 of 300
building tree 17 of 300
building tree 18 of 300
building tree 19 of 300
building tree 20 of 300
building tree 21 of 300
building tree 22 of 300
building tree 23 of 300
building tree 24 of 300
building tree 25 of 300
building tree 26 of 300
building tree 27 of 300
building tree 28 of 300
building tree 29 of 300
building tree 30 of 300
building tree 31 of 300
building tree 32 of 300
building tree 33 of 300
building tree 34 of 300
building tree 35 of 300
building tree 36 of 300
building tree 37 of 300
building tree 38 of 300
building tree 39 of 300
building tree 40 of 300

[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   24.8s

building tree 41 of 300
building tree 42 of 300
building tree 43 of 300
building tree 44 of 300
building tree 45 of 300
building tree 46 of 300
building tree 47 of 300
building tree 48 of 300
building tree 49 of 300
building tree 50 of 300
building tree 51 of 300
building tree 52 of 300
building tree 53 of 300
building tree 54 of 300
building tree 55 of 300
building tree 56 of 300
building tree 57 of 300
building tree 58 of 300
building tree 59 of 300
building tree 60 of 300
building tree 61 of 300
building tree 62 of 300
building tree 63 of 300
building tree 64 of 300
building tree 65 of 300
building tree 66 of 300
building tree 67 of 300
building tree 68 of 300
building tree 69 of 300
building tree 70 of 300
building tree 71 of 300
building tree 72 of 300
building tree 73 of 300
building tree 74 of 300
building tree 75 of 300
building tree 76 of 300
building tree 77 of 300
building tree 78 of 300
building tree 79 of 300
building tree 80 of 300
building tree 81 of 300
building tree 82 of 300
building tree 83 of 300
building tree 84 of 300
building tree 85 of 300
building tree 86 of 300
building tree 87 of 300
building tree 88 of 300
building tree 89 of 300
building tree 90 of 300
building tree 91 of 300
building tree 92 of 300
building tree 93 of 300
building tree 94 of 300
building tree 95 of 300
building tree 96 of 300
building tree 97 of 300
building tree 98 of 300
building tree 99 of 300
building tree 100 of 300
building tree 101 of 300
building tree 102 of 300
building tree 103 of 300
building tree 104 of 300
building tree 105 of 300
building tree 106 of 300
building tree 107 of 300
building tree 108 of 300
building tree 109 of 300
building tree 110 of 300
building tree 111 of 300
building tree 112 of 300
building tree 113 of 300
building tree 114 of 300
building tree 115 of 300
building tree 116 of 300
building tree 117 of 300
building tree 118 of 300
building tree 119 of 300
building tree 120 of 300
building tree 121 of 300
building tree 122 of 300
building tree 123 of 300
building tree 124 of 300
building tree 125 of 300
building tree 126 of 300
building tree 127 of 300
building tree 128 of 300
building tree 129 of 300
building tree 130 of 300
building tree 131 of 300
building tree 132 of 300
building tree 133 of 300
building tree 134 of 300
building tree 135 of 300
building tree 136 of 300
building tree 137 of 300
building tree 138 of 300
building tree 139 of 300
building tree 140 of 300
building tree 141 of 300
building tree 142 of 300
building tree 143 of 300
building tree 144 of 300
building tree 145 of 300
building tree 146 of 300
building tree 147 of 300
building tree 148 of 300
building tree 149 of 300
building tree 150 of 300
building tree 151 of 300
building tree 152 of 300
building tree 153 of 300
building tree 154 of 300
building tree 155 of 300
building tree 156 of 300
building tree 157 of 300
building tree 158 of 300
building tree 159 of 300
building tree 160 of 300

[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  1.7min

building tree 161 of 300
building tree 162 of 300
building tree 163 of 300
building tree 164 of 300
building tree 165 of 300
building tree 166 of 300
building tree 167 of 300
building tree 168 of 300
building tree 169 of 300
building tree 170 of 300
building tree 171 of 300
building tree 172 of 300
building tree 173 of 300
building tree 174 of 300
building tree 175 of 300
building tree 176 of 300
building tree 177 of 300
building tree 178 of 300
building tree 179 of 300
building tree 180 of 300
building tree 181 of 300
building tree 182 of 300
building tree 183 of 300
building tree 184 of 300
building tree 185 of 300
building tree 186 of 300
building tree 187 of 300
building tree 188 of 300
building tree 189 of 300
building tree 190 of 300
building tree 191 of 300
building tree 192 of 300
building tree 193 of 300
building tree 194 of 300
building tree 195 of 300
building tree 196 of 300
building tree 197 of 300
building tree 198 of 300
building tree 199 of 300
building tree 200 of 300
building tree 201 of 300
building tree 202 of 300
building tree 203 of 300
building tree 204 of 300
building tree 205 of 300
building tree 206 of 300
building tree 207 of 300
building tree 208 of 300
building tree 209 of 300
building tree 210 of 300
building tree 211 of 300
building tree 212 of 300
building tree 213 of 300
building tree 214 of 300
building tree 215 of 300
building tree 216 of 300
building tree 217 of 300
building tree 218 of 300
building tree 219 of 300
building tree 220 of 300
building tree 221 of 300
building tree 222 of 300
building tree 223 of 300
building tree 224 of 300
building tree 225 of 300
building tree 226 of 300
building tree 227 of 300
building tree 228 of 300
building tree 229 of 300
building tree 230 of 300
building tree 231 of 300
building tree 232 of 300
building tree 233 of 300
building tree 234 of 300
building tree 235 of 300
building tree 236 of 300
building tree 237 of 300
building tree 238 of 300
building tree 239 of 300
building tree 240 of 300
building tree 241 of 300
building tree 242 of 300
building tree 243 of 300
building tree 244 of 300
building tree 245 of 300
building tree 246 of 300
building tree 247 of 300
building tree 248 of 300
building tree 249 of 300
building tree 250 of 300
building tree 251 of 300
building tree 252 of 300
building tree 253 of 300
building tree 254 of 300
building tree 255 of 300
building tree 256 of 300
building tree 257 of 300
building tree 258 of 300
building tree 259 of 300
building tree 260 of 300
building tree 261 of 300
building tree 262 of 300
building tree 263 of 300
building tree 264 of 300
building tree 265 of 300
building tree 266 of 300
building tree 267 of 300
building tree 268 of 300
building tree 269 of 300
building tree 270 of 300
building tree 271 of 300
building tree 272 of 300
building tree 273 of 300
building tree 274 of 300
building tree 275 of 300
building tree 276 of 300
building tree 277 of 300
building tree 278 of 300
building tree 279 of 300
building tree 280 of 300
building tree 281 of 300
building tree 282 of 300
building tree 283 of 300
building tree 284 of 300
building tree 285 of 300
building tree 286 of 300
building tree 287 of 300
building tree 288 of 300
building tree 289 of 300
building tree 290 of 300
building tree 291 of 300
building tree 292 of 300
building tree 293 of 300
building tree 294 of 300
building tree 295 of 300
building tree 296 of 300
building tree 297 of 300
building tree 298 of 300
building tree 299 of 300
building tree 300 of 300

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  3.3min finished

RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=3, verbose=2)

In [ ]:
model_ridge = Ridge()
model_ridge.fit(X_train, Y_train)

Ridge()

In [ ]:
model_adaboost = AdaBoostRegressor(n_estimators=300)
model_adaboost.fit(X_test, Y_test)

AdaBoostRegressor(n_estimators=300)

In [ ]:
model_adaboost.score(X_test, Y_test)

-1.3190648717941267

In [ ]:
model_ridge.score(X_test, Y_test)

0.17681305212215304

In [ ]:
model_randomF_simple2 = RandomForestRegressor(random_state=3)

# Hyperparameter grid
param_grid = {
    "n_estimators": [200, 300],         # number of trees
    "max_depth": [None, 10, 20, 30],         # tree depth
    "min_samples_split": [2, 5, 10],         # min samples to split a node
    "min_samples_leaf": [1, 2, 4],           # min samples at a leaf
    "max_features": ["sqrt", "log2", None],   # number of features to consider
    "verbose" : [2]
}

# GridSearchCV setup
grid_search = GridSearchCV(
    estimator=model_randomF_simple2,
    param_grid=param_grid,
    cv=4,              # 3-fold cross validation
    n_jobs=-1,
    verbose=2,
    scoring="r2"       # or "neg_mean_squared_error" depending on your goal
)

# Fit
grid_search.fit(X_train[important_feat], Y_train)

Fitting 4 folds for each of 216 candidates, totalling 864 fits

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

KeyboardInterrupt:

In [ ]:
model_svr_simple.score(X_test[important_feat], Y_test)

0.02686221881856632

In [ ]:
model_randomF_simple.score(X_test[important_feat], Y_test)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  37 tasks      | elapsed:    0.4s
[Parallel(n_jobs=2)]: Done 158 tasks      | elapsed:    1.7s
[Parallel(n_jobs=2)]: Done 300 out of 300 | elapsed:    3.1s finished

0.07531902679707936

In [ ]:
model_randomF_simple2.score(X_test[important_feat], Y_test)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  37 tasks      | elapsed:    0.4s
[Parallel(n_jobs=2)]: Done 158 tasks      | elapsed:    2.1s
[Parallel(n_jobs=2)]: Done 200 out of 200 | elapsed:    2.9s finished

0.46419005870321506

In [ ]:
X_test

,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,created_at_month,created_at_day,created_at_hour,created_at_minutes,actual_delivery_time_month,actual_delivery_time_day,actual_delivery_time_hour,actual_delivery_time_minutes
62050,45,5,-1.189868,-1.179071,-1.195571,0.101199,-0.918420,0.153306,0.483156,-0.172589,-0.650744,-0.631820,1,26,3,18,1,26,3,55
55548,41,1,-0.499343,0.281290,-1.195571,1.683503,0.649218,-0.829994,-0.783962,-0.604534,1.525031,-0.062219,2,16,1,53,2,16,2,59
30675,45,4,0.881706,0.906688,1.417316,-1.069450,-0.059764,-0.611483,-0.707167,-0.756985,1.525031,-1.698616,2,8,19,18,2,8,19,49
98705,20,5,-1.189868,-0.876273,-1.195571,1.415926,0.376129,1.282281,1.366298,1.936319,-0.650744,0.541172,1,23,19,29,1,23,20,16
103547,4,1,1.572231,0.445478,2.288278,-0.889350,0.124046,-1.376272,-1.359924,-1.188930,1.525031,1.048021,1,24,3,17,1,24,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96625,23,1,0.881706,1.347272,1.417316,0.386785,0.257965,1.282281,1.635081,1.326515,1.525031,1.279723,2,2,1,6,2,2,1,51
108559,13,4,-0.499343,-0.117215,-1.195571,0.299308,-0.700474,1.245862,1.097516,1.860094,-0.650744,0.159829,2,1,2,54,2,1,3,59
91135,44,2,-0.499343,-0.587501,-0.324609,-0.758134,0.113543,-0.575064,-0.745564,-0.756985,-0.650744,0.714949,2,15,1,40,2,15,2,23
32355,13,5,-0.499343,-0.113915,-0.324609,0.783005,-0.149043,0.626747,0.559951,0.437216,-0.650744,0.507382,2,17,20,17,2,17,21,1
136126,57,3,0.191182,-0.084213,0.546354,-0.915078,-0.689970,0.408236,0.905528,-0.020138,-0.650744,0.912861,1,25,3,55,1,25,4,41

In [ ]:
Y_test

62050     2192
55548     3941
30675     1870
98705     2782
103547    2741
          ...
96625     2706
108559    3906
91135     2610
32355     2635
136126    2725
Name: Delivery_Duration, Length: 27297, dtype: int64

In [ ]:
model_svr_simple.predict(X_test.loc[[108559], important_feat])

array([2788.61982117])

In [ ]:
model_randomF_simple.predict(X_test.loc[[108559], important_feat])

array([2999.66])

In [ ]:
grid.fit(X_train, Y_train)

KeyboardInterrupt: